### ISSUE TITLE
Sync dev with main on new tag

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#437]
### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like

Dev sould sync with main on new tag (e.g. `v0.0.1`)

Dev should sync with beta if the tag ends with an b (e.g. `v0.0.1b`)

### Describe alternatives you've considered

None

### Additional context

None

**Comment by 0xWDG** [comment]
Stable (main) (pseudo)
```YAML
on:
 push:
  tags:
   - 'v*'
```

beta (pseudo)
```YAML
on:
 push:
  tags:
   - 'v*b'
```
