### ISSUE TITLE
Website->Create account, border missing

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#503]
### Description

<img width="515" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/23712625-eb2c-408d-9d87-eb6c03599741">

If a field is highlighted, it loses it's border.

### To Reproduce

Highlight a field.

### Expected behavior

See the border

### Version information

N/A

**Comment by 0xWDG** [comment]
The problem:

```css
input[type="text"]:focus, input[type="password"]:focus, input[type="email"]:focus {
    outline: none;
    border: none;
}
```

https://github.com/AuroraEditor/auroraeditor.com/blob/main/src/Assets/aurora/styles/Auth/aurora-register.css#L226-L229
